[project]
    name            = "configs"
    version         = "0.1.0"
    description     = "get clash subscribe using python"
    readme          = "README.md"
    requires-python = ">=3.12"
    dependencies    = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
